# Generated by Django 4.2.3 on 2023-09-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_expense_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Personal Care', 'Personal Care'), ('Taxes', 'Taxes'), ('Food', 'Food '), ('Healthcare', 'Healthcare'), ('Utilities', 'Utilities'), ('Fun', 'Fun'), ('Gifts', 'Gifts'), ('Home Supplies', 'Home Supplies'), ('Clothes', 'Clothes'), ('Other', 'Other')], max_length=50),
        ),
    ]
